#!/usr/bin/env python3
"""
Генератор конфигурационных файлов Refloat из src/conf/settings.xml.

Замена `vesc_tool --xmlConfToCode` для сборок, где бинарник VESC Tool недоступен
(host-тесты, CI). Формат сериализации выведен из эталонных файлов, сгенерированных
VESC Tool (refloat-upstream/vesc_pkg_lib/examples/config/conf/), и воспроизводит их
байт-в-байт по структуре.

ВНИМАНИЕ: signature считается нашим алгоритмом и НЕ совпадает с сигнатурой VESC Tool.
Для прошивки, которая должна общаться с VESC Tool, источником истины остаётся
зафиксированная версия vesc_tool (см. docs/threading_model.md, раздел Build).

Выводит:
  <out>/conf/conf_default.h
  <out>/conf/confparser.h
  <out>/conf/confparser.c
  <out>/conf/confxml.h
  <out>/conf/confxml.c
  <out>/conf/conf_general.h
"""

import argparse
import os
import re
import xml.etree.ElementTree as ET
import zlib
import zipfile  # noqa: F401  (документирует зависимость от zlib-формата qCompress)

# Тип параметра в settings.xml
T_SECTION, T_DOUBLE, T_INT, T_STRING, T_ENUM, T_BOOL = '0', '1', '2', '3', '4', '5'

# vTx → (сериализатор, десериализатор, нужен ли scale)
# Выведено из эталонных файлов VESC Tool:
#   vTx=3 → uint16, vTx=7 → float16(scale), vTx=9 → float32_auto
# Остальные — по регулярности нумерации VESC_TX_T.
VTX = {
    '1': ('uint8', False),
    '2': ('int8', False),
    '3': ('uint16', False),
    '4': ('int16', False),
    '5': ('uint32', False),
    '6': ('int32', False),
    '7': ('float16', True),
    '8': ('float32', True),
    '9': ('float32_auto', False),
}

WIDTH = {'uint8': 1, 'int8': 1, 'uint16': 2, 'int16': 2, 'uint32': 4, 'int32': 4,
         'float16': 2, 'float32': 4, 'float32_auto': 5}

HDR = "// This file is autogenerated by tools/gen_conf.py (VESC Tool replacement)\n"


def text(node, tag, default=''):
    e = node.find(tag)
    return (e.text or '') if e is not None else default


def parse(path):
    root = ET.parse(path).getroot()
    params = {}
    for p in root.find('Params'):
        params[p.tag] = {c.tag: (c.text or '') for c in p}
    order = [e.text for e in root.find('SerOrder')]
    return params, order


def struct_name(params):
    return params['config_name']['valString']


def emit_serializer(name, d):
    t = d['type']
    if t in (T_ENUM, T_BOOL):
        return f"\tbuffer[ind++] = conf->{name};", f"\tconf->{name} = buffer[ind++];", 1
    kind, needs_scale = VTX[d['vTx']]
    if kind in ('uint8', 'int8'):
        return (f"\tbuffer[ind++] = conf->{name};",
                f"\tconf->{name} = buffer[ind++];", 1)
    if needs_scale:
        scale = d['vTxDoubleScale']
        return (f"\tbuffer_append_{kind}(buffer, conf->{name}, {scale}, &ind);",
                f"\tconf->{name} = buffer_get_{kind}(buffer, {scale}, &ind);",
                WIDTH[kind])
    ctype = {'uint16': 'uint16_t', 'int16': 'int16_t',
             'uint32': 'uint32_t', 'int32': 'int32_t'}.get(kind)
    cast = f"({ctype}) " if ctype else ""
    return (f"\tbuffer_append_{kind}(buffer, {cast}conf->{name}, &ind);",
            f"\tconf->{name} = buffer_get_{kind}(buffer, &ind);",
            WIDTH[kind])


def default_value(d):
    t = d['type']
    if t == T_DOUBLE:
        return d.get('valDouble', '0')
    if t in (T_INT, T_ENUM, T_BOOL):
        return d.get('valInt', '0')
    return '0'


def signature(params, order):
    """Детерминированный хеш описания конфигурации (аналог сигнатуры VESC Tool)."""
    blob = ''.join(
        f"{n}:{params[n]['type']}:{params[n].get('vTx','')}:{params[n].get('vTxDoubleScale','')};"
        for n in order
    )
    return zlib.crc32(blob.encode()) & 0x7FFFFFFF


def gen(settings, out_dir, version, package_name, git_hash):
    params, order = parse(settings)
    sname = struct_name(params)
    lo, up = sname.lower(), sname.upper()
    sig = signature(params, order)

    ser_lines, deser_lines, defaults, dflt_h = [], [], [], []
    size = 4  # signature
    for n in order:
        d = params[n]
        if d['type'] in (T_SECTION, T_STRING):
            continue
        s, ds, w = emit_serializer(n, d)
        ser_lines.append(s)
        deser_lines.append(ds)
        size += w
        cdef = d.get('cDefine', '').strip()
        if cdef:
            defaults.append(f"\tconf->{n} = {cdef};")
            dflt_h.append(f"// {d.get('longName', n)}\n#ifndef {cdef}\n"
                          f"#define {cdef} {default_value(d)}\n#endif\n")
        else:
            defaults.append(f"\tconf->{n} = {default_value(d)};")

    os.makedirs(os.path.join(out_dir, 'conf'), exist_ok=True)

    def write(rel, content):
        with open(os.path.join(out_dir, 'conf', rel), 'w') as f:
            f.write(content)

    write('conf_default.h', HDR + "\n#ifndef CONF_DEFAULT_H_\n#define CONF_DEFAULT_H_\n\n"
          + "\n".join(dflt_h) + "\n// CONF_DEFAULT_H_\n#endif\n")

    write('confparser.h', HDR + f"""
#ifndef CONFPARSER_H_
#define CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define {up}_SIGNATURE\t\t{sig}
// Верхняя оценка размера сериализованной конфигурации
#define {up}_SERIALIZED_MAX\t\t{size}

// Functions
int32_t confparser_serialize_{lo}(uint8_t *buffer, const {sname} *conf);
bool confparser_deserialize_{lo}(const uint8_t *buffer, {sname} *conf);
void confparser_set_defaults_{lo}({sname} *conf);

// CONFPARSER_H_
#endif
""")

    write('confparser.c', HDR + f"""
#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "confparser.h"

int32_t confparser_serialize_{lo}(uint8_t *buffer, const {sname} *conf) {{
\tint32_t ind = 0;

\tbuffer_append_uint32(buffer, {up}_SIGNATURE, &ind);

""" + "\n".join(ser_lines) + f"""

\treturn ind;
}}

bool confparser_deserialize_{lo}(const uint8_t *buffer, {sname} *conf) {{
\tint32_t ind = 0;

\tuint32_t signature = buffer_get_uint32(buffer, &ind);
\tif (signature != {up}_SIGNATURE) {{
\t\treturn false;
\t}}

""" + "\n".join(deser_lines) + f"""

\treturn true;
}}

void confparser_set_defaults_{lo}({sname} *conf) {{
""" + "\n".join(defaults) + """
}
""")

    # confxml: qCompress-совместимый блоб (4 байта big-endian длины + zlib)
    raw = open(settings, 'rb').read()
    comp = len(raw).to_bytes(4, 'big') + zlib.compress(raw, 9)
    rows = []
    for i in range(0, len(comp), 16):
        rows.append("\t" + ", ".join(f"0x{b:02x}" for b in comp[i:i + 16]) + ",")
    write('confxml.h', HDR + f"""
#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_{up}__SIZE\t\t{len(comp)}

// Variables
extern uint8_t data_{lo}_[];

// CONFXML_H_
#endif
""")
    write('confxml.c', HDR + f'\n#include "confxml.h"\n\nuint8_t data_{lo}_[{len(comp)}] = {{\n'
          + "\n".join(rows) + "\n};\n")

    # conf_general.h из шаблона
    tmpl = open(os.path.join(os.path.dirname(settings), 'conf_general.h.in')).read()
    m = re.match(r'(\d+)\.(\d+)\.(\d+)(?:-(.*))?', version)
    subs = {
        'PACKAGE_NAME': package_name[:20],
        'VERSION': version,
        'MAJOR_VERSION': m.group(1), 'MINOR_VERSION': m.group(2),
        'PATCH_VERSION': m.group(3), 'VERSION_SUFFIX': (m.group(4) or '')[:20],
        'GIT_HASH': git_hash[:8],
    }
    for k, v in subs.items():
        tmpl = tmpl.replace('{{' + k + '}}', v)
    write('conf_general.h', tmpl)

    print(f"gen_conf: {len(order)} params, serialized <= {size} B, "
          f"signature {sig}, confxml {len(comp)} B -> {out_dir}/conf/")
    return size


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--settings', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--version', default='0.0.0')
    ap.add_argument('--package-name', default='Refloat')
    ap.add_argument('--git-hash', default='00000000')
    a = ap.parse_args()
    gen(a.settings, a.out, a.version, a.package_name, a.git_hash)
