#!/usr/bin/env python3
"""
Генератор таблицы описания Motor Configuration из схемы VESC Tool.

Virtual mcConfig отдаёт VESC Tool блоб, который тот разбирает как настоящую
конфигурацию мотора. Чтобы разбор состоялся, нужны две вещи:

  * точная сигнатура — CRC32C по name+type+vTx+enumNames всех параметров
    в порядке SerOrder (ConfigParams::getSignature);
  * точный порядок и кодировка всех ~200 параметров (ConfigParams::deSerialize
    последовательно вычитывает их из буфера).

Алгоритм сигнатуры сверен с эталоном: для примера конфигурации из
vesc_pkg_lib он даёт 32903057 — значение, записанное самим VESC Tool
в сгенерированный им confparser.h.

Источник схемы: <vesc_tool>/res/config/<версия>/parameters_mcconf.xml.
Схема зависит от версии VESC Tool, поэтому генерируется по одной таблице
на версию, а нужная выбирается в рантайме.

Использование:
    python3 tools/gen_mcconf.py \
        --xml /path/to/vesc_tool/res/config/6.06/parameters_mcconf.xml \
        --version 6.06 \
        --out compat/vesc_protocol/generated
"""

import argparse
import json
import os
import xml.etree.ElementTree as ET

# CFG_T из vesc_tool/datatypes.h
T_UNDEF, T_DOUBLE, T_INT, T_QSTRING, T_ENUM, T_BOOL, T_BITFIELD = range(7)

# VESC_TX_T из vesc_tool/datatypes.h
TX_UNDEF, TX_UINT8, TX_INT8, TX_UINT16, TX_INT16, TX_UINT32, TX_INT32, \
    TX_DOUBLE16, TX_DOUBLE32, TX_DOUBLE32_AUTO = range(10)

# Соответствие (type, vTx) → способ кодирования и размер в байтах
KIND = {
    (T_DOUBLE, TX_DOUBLE16): ("MC_KIND_DOUBLE16", 2),
    (T_DOUBLE, TX_DOUBLE32): ("MC_KIND_DOUBLE32", 4),
    (T_DOUBLE, TX_DOUBLE32_AUTO): ("MC_KIND_DOUBLE32_AUTO", 4),
    (T_INT, TX_UINT8): ("MC_KIND_U8", 1),
    (T_INT, TX_INT8): ("MC_KIND_I8", 1),
    (T_INT, TX_UINT16): ("MC_KIND_U16", 2),
    (T_INT, TX_INT16): ("MC_KIND_I16", 2),
    (T_INT, TX_UINT32): ("MC_KIND_U32", 4),
    (T_INT, TX_INT32): ("MC_KIND_I32", 4),
}


def crc32c(data: bytes) -> int:
    """Utility::crc32c из VESC Tool."""
    crc = 0xFFFFFFFF
    for b in data:
        crc ^= b
        for _ in range(8):
            mask = -(crc & 1) & 0xFFFFFFFF
            crc = (crc >> 1) ^ (0x82F63B78 & mask)
    return (~crc) & 0xFFFFFFFF


def parse(path):
    root = ET.parse(path).getroot()
    params = {}
    for p in root.find("Params"):
        d = {c.tag: (c.text or "") for c in p}
        d["enumNames"] = [(e.text or "") for e in p.findall("enumNames")]
        params[p.tag] = d
    order = [e.text for e in root.find("SerOrder")]
    return params, order


def signature(params, order) -> int:
    """ConfigParams::getSignature()."""
    s = ""
    for name in order:
        s += name
        d = params.get(name)
        if d is None:
            continue
        s += str(int(d.get("type") or 0))
        s += str(int(d.get("vTx") or 0))
        s += "".join(d["enumNames"])
    return crc32c(s.encode("utf-8"))


def classify(d):
    """→ (макрос вида кодирования, размер, масштаб, значение по умолчанию)"""
    t = int(d.get("type") or 0)
    v = int(d.get("vTx") or 0)

    # enum / bool / bitfield кодируются одним байтом независимо от vTx
    if t in (T_ENUM, T_BOOL, T_BITFIELD):
        return "MC_KIND_BYTE", 1, 1.0, float(int(d.get("valInt") or 0))

    if t == T_DOUBLE:
        scale = float(d.get("vTxDoubleScale") or 1.0)
        default = float(d.get("valDouble") or 0.0)
    elif t == T_INT:
        scale = 1.0
        default = float(int(d.get("valInt") or 0))
    else:
        raise SystemExit(f"неподдерживаемый тип параметра: type={t}, vTx={v}")

    key = (t, v)
    if key not in KIND:
        raise SystemExit(f"неизвестная пара type={t}, vTx={v}")
    kind, size = KIND[key]
    return kind, size, scale, default


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xml", required=True)
    ap.add_argument("--version", required=True, help="версия VESC Tool, например 6.06")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    params, order = parse(a.xml)
    sig = signature(params, order)

    rows, meta, total = [], [], 4  # 4 байта сигнатуры
    for name in order:
        d = params[name]
        kind, size, scale, default = classify(d)
        rows.append(f'    {{"{name}", {kind}, {scale}f, {default}f}},')
        meta.append({"name": name, "kind": kind, "size": size,
                     "scale": scale, "default": default, "offset": total})
        total += size

    tag = a.version.replace(".", "_")
    os.makedirs(a.out, exist_ok=True)

    with open(os.path.join(a.out, f"mcconf_schema_{tag}.c"), "w") as f:
        f.write(f"""// Autogenerated by tools/gen_mcconf.py — НЕ РЕДАКТИРОВАТЬ.
//
// Схема Motor Configuration VESC Tool {a.version}
// Источник: <vesc_tool>/res/config/{a.version}/parameters_mcconf.xml
//
// Параметров: {len(order)}, размер блоба: {total} байт, сигнатура: {sig}

#include "../virtual_mcconf.h"

static const McParam params_{tag}[] = {{
""" + "\n".join(rows) + f"""
}};

const McConfSchema mcconf_schema_{tag} = {{
    .version = "{a.version}",
    .signature = {sig}u,
    .params = params_{tag},
    .param_count = {len(order)},
    .blob_size = {total},
}};
""")

    with open(os.path.join(a.out, f"mcconf_schema_{tag}.json"), "w") as f:
        json.dump({"version": a.version, "signature": sig, "blob_size": total,
                   "params": meta}, f, indent=1)

    print(f"gen_mcconf: {a.version}: {len(order)} параметров, блоб {total} байт, "
          f"сигнатура {sig}")


if __name__ == "__main__":
    main()
