#!/usr/bin/env python3
"""
Подготовка QML-интерфейса Refloat для отдачи через COMM_GET_QML_UI_APP.

VESC Tool ожидает данные в формате qCompress: 4 байта big-endian с размером
несжатых данных, дальше zlib-поток (см. qUncompress в vescinterface.cpp).

Подстановки {{PACKAGE_NAME}} и {{VERSION}} делаются так же, как в Makefile
самого Refloat, чтобы UI не отличался от upstream-сборки.
"""

import argparse
import os
import zlib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--qml-in', required=True)
    ap.add_argument('--out', required=True, help='каталог для qml_app.c/h')
    ap.add_argument('--package-name', default='Refloat')
    ap.add_argument('--version', default='0.0.0')
    a = ap.parse_args()

    src = open(a.qml_in, encoding='utf-8').read()
    src = src.replace('{{PACKAGE_NAME}}', a.package_name[:20]).replace('{{VERSION}}', a.version)
    raw = src.encode('utf-8')
    blob = len(raw).to_bytes(4, 'big') + zlib.compress(raw, 9)

    os.makedirs(a.out, exist_ok=True)
    rows = []
    for i in range(0, len(blob), 16):
        rows.append('    ' + ', '.join(f'0x{b:02x}' for b in blob[i:i + 16]) + ',')

    with open(os.path.join(a.out, 'qml_app.h'), 'w') as f:
        f.write('// Autogenerated by tools/gen_qml.py\n#pragma once\n\n'
                '#include <stddef.h>\n#include <stdint.h>\n\n'
                f'#define QML_APP_SIZE {len(blob)}\n\n'
                'extern const uint8_t qml_app_data[QML_APP_SIZE];\n')

    with open(os.path.join(a.out, 'qml_app.c'), 'w') as f:
        f.write('// Autogenerated by tools/gen_qml.py\n#include "qml_app.h"\n\n'
                f'const uint8_t qml_app_data[QML_APP_SIZE] = {{\n' + '\n'.join(rows) + '\n};\n')

    print(f'gen_qml: {len(raw)} B QML -> {len(blob)} B qCompress -> {a.out}/qml_app.c')


if __name__ == '__main__':
    main()
